services:
  - type: web
    name: vanilla-fashion-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
